### PR TITLE
chore: add USDCEUR config

### PR DESCRIPTION
**Pull request by tobikuhlmann**
## Description
Add USDCEUR configs

## Other changes

No

## Tested

Ran the client locally with USDCEUR rates: 
```
[
  [
  {exchange: 'KRAKEN', symbol: 'USDCEUR', toInvert: false}
  ],
  [
  {exchange: 'COINBASE', symbol: 'USDTUSDC', toInvert: true},
  {exchange: 'COINBASE', symbol: 'USDTEUR', toInvert: false}
  ],
  [
  {exchange: 'WHITEBIT', symbol: 'USDCUSDT', toInvert: false},
  {exchange: 'COINBASE', symbol: 'USDTEUR', toInvert: false}
  ],
  [
  {exchange: 'KRAKEN', symbol: 'USDCUSD', toInvert: false},
  {exchange: 'KRAKEN', symbol: 'EURUSD', toInvert: true}
  ],
]
```
## Related issues

- Fixes part of https://github.com/mento-protocol/mento-general/issues/164

## Backwards compatibility

fully

### CODE REVIEW

**Comment by sissnad** [comment]
> [
>   {exchange: 'KRAKEN', symbol: 'USDTUSD', toInvert: false},
>   {exchange: 'KRAKEN', symbol: 'EURUSD', toInvert: true}
>   ]

This should be 
```ts
[
  {exchange: 'KRAKEN', symbol: 'USDCUSD', toInvert: false},
  {exchange: 'KRAKEN', symbol: 'EURUSD', toInvert: true}
  ]
```

**Comment by tobikuhlmann** [comment]
> > [
> > {exchange: 'KRAKEN', symbol: 'USDTUSD', toInvert: false},
> > {exchange: 'KRAKEN', symbol: 'EURUSD', toInvert: true}
> > ]
> 
> This should be
> 
> ```ts
> [
>   {exchange: 'KRAKEN', symbol: 'USDCUSD', toInvert: false},
>   {exchange: 'KRAKEN', symbol: 'EURUSD', toInvert: true}
>   ]
> ```

uff yes thanks, fixed

**Review by sissnad — APPROVED** [review]
Client config looks good! The price sources will have a separate PR I guess?

**Comment by tobikuhlmann** [comment]
> Client config looks good! The price sources will have a separate PR I guess?

yes, I'll add them to the celo-monorepo oracle helm charts

**Comment by nvtaveras** [comment]
closing as it was merged in #154

**Pull request closed without merging**
